version: '3.3'
services :
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"